### ISSUE TITLE
Filling Nan's 

### ISSUE THREAD

**Issue by work-mohit** [asingleneuron/hackathons_solution#1]
hey ! why you choose to fill mode in place of Nan's can you please explain ! ( Mean why you thought the mode will work )

**Comment by asingleneuron** [comment]
For categorical features, **imputing with most frequent ( mode ) is the best guess.** 
But sometimes missing values ratios are bigger than you can just try imputing with a new category or leave it as it is, if you are choosing a model which is capable of handling NaN values.
